### ISSUE TITLE
load AAA-exported traces

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#112]
Related to #81, AAA-exported splines (traces) should be loadable.

One of the problems with this is that AAA can export splines with arbitrary amounts of metadata.  The current example AAA data (Qumuq) includes what is probably close to a bare minimum of metadata to match the splines to frames in the ULT files.

**Comment by keggsmurph21** [comment]
What is AAA?

**Comment by jonorthwash** [comment]
http://www.articulateinstruments.com/aaa/

**Comment by keggsmurph21** [comment]
> The standard base edition of AAA includes facilities for analysing EPG data. More to follow.

lmao, hopefully it will follow :^)

Thanks, @jonorthwash !

**Comment by jonorthwash** [comment]
If you click on the AAA tab [downloads page](www.articulateinstruments.com/downloads/), there's a lot more info.

**Comment by mr-martian** [comment]
I have now, in some sense, gotten data from `SPLINES.dat` into `metadata.json`. However, it will take some further experimentation to get the image dimensions right. It's also possible I'm associating them with the wrong frames and I'm wondering if there's a chance it might actually be in polar coordinates.

**Comment by jonorthwash** [comment]
Two things:
- The frames can be be exported in polar coordinates, but that's not how I chose to export them in this case.
- The image dimensions should be based on the edges of the frame.

**Comment by jonorthwash** [comment]
This is how tracing in AAA looks (with Qumuq data).
![Screenshot from 2019-12-29 12-44-32](https://user-images.githubusercontent.com/963849/71560539-0d212580-2a39-11ea-85b0-528e97b9d233.png)

**Comment by jonorthwash** [comment]
The are spaced at every _n°_ intersect, probably every 1°.

**Comment by mr-martian** [comment]
@jonorthwash I can't read the screen, could you tell me what file and frame that is?

**Comment by jonorthwash** [comment]
I'm not sure.  You can probably tell the former from the length of the target words in the list and the percent through the list it is, and the latter from the numbers under the image.  But it looks like the trace probably isn't right anyway.  The point was to show you what it looks like broadly.

I can look at traces and potentially assess what's wrong with them..

**Comment by mr-martian** [comment]
![Screenshot from 2019-12-29 20-12-13](https://user-images.githubusercontent.com/5350777/71564994-935c5c80-2a77-11ea-9a86-c13c70e25291.png)
I think I figured it out.

**Comment by mr-martian** [comment]
It currently imports all traces as red and ignores anything with a set confidence interval below 50.

It also assumes that all columns in `SPLINES.dat` past the first 3 are either rectangular coordinates or confidence intervals, which might not be entirely true.

**Comment by jonorthwash** [comment]
> It currently imports all traces as red and ignores anything with a set confidence interval below 50.

It seems it is importing them into the different layers though ("Tongue", "Roof"), so recolouring is straightforward.

A few things I see:
- A black background would be good for the images, instead of white
- The frames in the `frames` tier aren't lining up with the annotations in the `annotation_0` tier.
- The "Read scan line data" should be selected by default if it's the only one, so that ultrasound images are loaded when a file is loaded.
  - In general, I'm thinking this part needs a redesign.  I'm not sure what the right approach is, but I'm starting to think we want a menu on top.  Then the `Data` menu would have options for which format of data to read (with unavailable options greyed out), with the current one checked and whichever makes most sense chosen automatically.

**Comment by jonorthwash** [comment]
> It also assumes that all columns in `SPLINES.dat` past the first 3 are either rectangular coordinates or confidence intervals, which might not be entirely true.

Correct.  It should probably be based on substrings "X,Y values" and "Confidence values" in the headers, the former matching 84 columns and the latter matching 42.

**Comment by jonorthwash** [comment]
> * A black background would be good for the images, instead of white

→ #129 

> * The frames in the `frames` tier aren't lining up with the annotations in the `annotation_0` tier.

→ #127 

> * The "Read scan line data" should be selected by default if it's the only one, so that ultrasound images are loaded when a file is loaded.

→ #128 


> > It also assumes that all columns in `SPLINES.dat` past the first 3 are either rectangular coordinates or confidence intervals, which might not be entirely true.
> 
> Correct. It should probably be based on substrings "X,Y values" and "Confidence values" in the headers, the former matching 84 columns and the latter matching 42.

If this is what's being done now, then this should be fine.  I'm going to close this issue since the basic functionality is working.
