### ISSUE TITLE
alignment of frames and intervals

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#127]
Frames and intervals don't seem to always align.

In attached screenshot, the two black frames are the annotated ones that should align with the small interval in the "annotation_0" tier.
![Screenshot from 2020-01-02 14-29-20](https://user-images.githubusercontent.com/963849/71687861-aec3b200-2d6c-11ea-87ae-2bfd016fb0c1.png)

**Comment by jonorthwash** [comment]
The location in the spectrogram that they should both align to is much later in the file.

Praat seems to get it right.  See attached.
![Screenshot from 2020-01-02 14-35-50](https://user-images.githubusercontent.com/963849/71688153-49bc8c00-2d6d-11ea-99e0-651fa4bb7ea1.png)

**Comment by jonorthwash** [comment]
Also note that the frames tier proceeds much later than the rest of the file.

**Comment by jonorthwash** [comment]
It seems the behaviour is that if the "read scanline data" isn't selected, it doesn't load the TextGrid for the next selected file.

**Comment by jonorthwash** [comment]
However, the timing still appears to be off....  But the audio and the frames are misaligned with the spectrogram by the same amount.

**Comment by jonorthwash** [comment]
Two separate issues:
- Alignment of annotation tiers and frames tier: apparently due to the frames tier not loading right if just generated (because it's a different length?).  @mr-martian suggests reloading the TextGrid after generating frames tier will solve this.
- Alignment of TextGrid tiers (including frames) with spectrogram: due to the TextGrid being a different length (in this case longer) than the audio.  Will need to figure out some way to do padding of probably either spectrogram or TextGrid.

**Comment by mr-martian** [comment]
reloading implemented in 97e7b95

**Comment by mr-martian** [comment]
@jonorthwash is this still an issue?

**Comment by jonorthwash** [comment]
No, I believe these issues are resolved.
