### ISSUE TITLE
wxAssertionError with SetSizer

### ISSUE THREAD

**Issue by qiyoulu** [SwatPhonLab/UltraTrace#190]
When running the app, wx throws an assertion error
`Windows managed by the sizer associated with the given window must have this window as parent, otherwise they will not be repositioned correctly.`

at line 234
`self.panel.SetSizer(self.hbox)`
in `__main__.py`

and at line 93
`self.app.SetSizerAndFit(self.app.hbox)`
in `trace.py`

I looked around, and this might help:
https://github.com/vslavik/poedit/issues/745
although this example is in C++

**Comment by jonorthwash** [comment]
@qiyoulu, what OS and python version are you using?  I don't get this with Python 3.10.8 or 3.10.9 on two different Debian machines.

**Comment by qiyoulu** [comment]
> @qiyoulu, what OS and python version are you using? I don't get this with Python 3.10.8 or 3.10.9 on two different Debian machines.

I was using the Python 3.10.9 from Linuxbrew on Fedora, but it works fine natively. I'm not sure what the issue is, but I'll close this for now.
