### ISSUE TITLE
Missing the stft2level.pyx file?

### ISSUE THREAD

**Issue by keggsmurph21** [swatphonlab/UltraTrace#21]
Hey y'all!

I'm trying to run this locally, and I think the repo is missing the `stft2level.pyx` file.  Specifically, I'm running:
```bash
$ cd /path/to/ultratrace
$ ./install
running build_ext
cythoning stft2level.pyx to stft2level.c
error: /path/to/ultratrace/stft2level.pyx
$ ls
./  ../  dev/  .git/  .gitignore  install*  README.md  screenshot.png  setup.py  UltraTrace.py*
```

I remember the Cython integration being something that Ziv had worked on, but maybe this `install` script is just out of date (spoiler: it is :smile:)?

**Comment by mr-martian** [comment]
I removed it because we replaced the stft2level stuff with parselmouth but I forgot to check the install script.

**Comment by keggsmurph21** [comment]
Cool!  Thanks for the heads up :)
