### ISSUE TITLE
Click and drag to select time ranges seems to be broken

### ISSUE THREAD

**Issue by mr-martian** [SwatPhonLab/UltraTrace#79]
_Originally posted by @jonorthwash at 2019-09-13T18:53:46Z ([original issue](https://github.swarthmore.edu/PhonLab/dicom-annotator/issues/79))_

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2019-09-13T18:55:15Z_

Original issue: #70.

**Comment by mr-martian** [comment]
Shift+Click+Drag works for me.

**Comment by jonorthwash** [comment]
Ah, me too.  Something about UI part of this isn't great, but it does work.
