### ISSUE TITLE
proper logging support

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#85]
Everything printed to the console should use a proper logger, with "WARNING", "ERROR", "INFO", etc. type messages.

**Comment by keggsmurph21** [comment]
I actually have this implemented on my fork.  I'll merge upstream sometime this weekend.

**Comment by jonorthwash** [comment]
Oh, that's cool!  I'd actually started to poke at it too, but I'll wait for your pushes.

@keggsmurph21, this illustrates one reason why "commit early, commit often"¹² is a useful mantra.  It's often the first line of communication between collaborators.

Speaking of which, don't you have direct commit access to this repo?

¹ https://sethrobertson.github.io/GitBestPractices/#commit
² https://www.aclweb.org/anthology/J08-3010.pdf

**Comment by jonorthwash** [comment]
@keggsmurph21, any updates on this?

**Comment by keggsmurph21** [comment]
Sorry, I haven't gotten around to this yet.  I'll work on it now.

And yes, I do have direct commit access, but I had started working on rewriting some pieces of this lib, and decided to do that via a fork so that we could continue pushing this branch forward.  (I guess I could have also just made a new branch in this repository...)

**Comment by keggsmurph21** [comment]
Done, see 889358b

**Comment by jonorthwash** [comment]
This looks great.  It's worth noting that there are out-of-the-box logging libraries.  But this is nice and simple—additional dependencies are already a problem with UltraTrace...

I'm thinking it might be nice to put distributed libraries in a subdirectory somewhere to keep the main directory clean.

**Comment by keggsmurph21** [comment]
I'll open a separate issue

**Comment by keggsmurph21** [comment]
@jonorthwash see #88 

Also, regarding python's standard `logging` module (and other third party ones), we probably don't even need that level of complexity, since we'll (presumably?) only ever have one logger (i.e. the main app-level one) and one place to log to (i.e. `stderr`).
