### ISSUE TITLE
Using arrow keys to move between frames

### ISSUE THREAD

**Issue by BartholomaeusAstrum** [SwatPhonLab/UltraTrace#86]
When a text box becomes selected (e.g. when changing the offset of the audio and the frametimes), the arrow keys only move the cursor within the text box, and the body of the program no longer responds to it.

**Comment by mr-martian** [comment]
See #45 and #78. I understood the current behavior to be what we wanted. Arrows control both cursors and frames but not both at the same time.

**Comment by BartholomaeusAstrum** [comment]
Daniel let me know that <esc> has this functionality! All good
