### ISSUE TITLE
Manage non-standard libraries

### ISSUE THREAD

**Issue by keggsmurph21** [SwatPhonLab/UltraTrace#88]
It might be nice to keep a copy of all of the external libraries we depend on somewhere (e.g. under `/lib`) so that we don't have to rely on the user installing with `pip` or `conda` or whatever.

**Comment by jonorthwash** [comment]
Actually, what I meant wasn't putting external libraries into a folder—I'm happy with users using pip, etc.

What I had in mind was putting things like the new logging library and anything else we separate out from the main `UltraTrace.py` file into a subdirectory (as opposed to leaving them in the root directory) in order to keep the main directory of the repo clean.

**Comment by kmurphy4** [comment]
Ah, that makes sense.  I've actually been implementing something along these lines -- I pushed ~25 commits today that restructure the code formerly in in `UltraTrace.py` (without really rewriting any of it).

Have you checked that out?

**Comment by jonorthwash** [comment]
Oh my.  Yes, that's what I had in mind, I guess.  I wasn't imagining separating *everything* out [yet], but okay.

So... how is UltraTrace run now?

**Comment by kmurphy4** [comment]
Just `python3 -m ultratrace /path/to/data` (`-m` is for "module").

**Comment by jonorthwash** [comment]
> Just `python3 -m ultratrace /path/to/data` (`-m` is for "module").

From within the main code directory or from within the directory containing the code's root directory?

**Comment by jonorthwash** [comment]
Also, this is a little less than ideal.  Before we could just execute the `UltraTrace.py` script, either from within the directory or from elsewhere, e.g.
```
$ /path/to/UltraTrace/UltraTrace.py /path/to/data
```
Is there a way we could make it this easy again?

**Comment by kmurphy4** [comment]
From within the repo's main directory:

```
$ git clone [...]/ultratrace
$ cd ultratrace
$ python3 -m ultratrace /path/to/data
```

I'll add a little executable wrapper tomorrow that will restore this
functionality to something like:

```
$ /path/to/ultratrace /path/to/data
```

Sorry for the confusion, but I think using Python native modules is the
best way to go, even if it makes calling a bit awkward (since this allows
us to have hierarchical imports & such).

**Comment by kmurphy4** [comment]
Regarding portability of the executable wrapper, can I assume that this
will only be run on MacOS & Linux? I don't have a Windows environment to
test with.

**Comment by keggsmurph21** [comment]
I added an executable and an installation script [here](https://github.com/SwatPhonLab/UltraTrace/compare/1e16e1946fecc23b120b5bd130b53fde5e010f68..3f99f476d0bf460b42dab8d028a2eb33d05dc17e).  They work on my Ubuntu system, but I haven't had the chance to test on MacOS (I'm a little worried about the `readlink` command ... I'm not sure MacOS calls it the same thing).

The executable gives you the same behavior as before:
```
$ /path/to/ultratrace/bin/ultratrace /path/to/data
```

And the `install` script (at the moment) just places a symlink into a prefix of your choosing (by default into `/usr/local/bin`, which should be on your path).  That way you can do things like:
```
$ sudo /path/to/ultratrace/bin/install # only needs to be run once
$ ultratrace /path/to/data
```

Is this the functionality you expect?

**Comment by jonorthwash** [comment]
> I think using Python native modules is the best way to go

I agree.

> I added an executable and an installation script

Thanks.  Yes, this looks like the right approach.  I can test on Debian, Mac, and Windows and let you know.

(I don't even know how to run python stuff on Windows, but I guess I'll figure it out.  Maybe I'll try WSL?)

In the future, that installation script could (should?) check/install/update external dependencies, with the method for doing so depending on the OS.  We could also do some virtualisation or something to test that it all works in a vanilla environment?

One way to do an installation script is as a Makefile, like the following excerpt of what I used for Ling 073 misc tools:

```
PREFIX ?= ~
install:
	@install -d $(DESTDIR)$(PREFIX)/bin
	install -m755 morph-test.py $(DESTDIR)$(PREFIX)/bin/morph-test
	install -m755 morphTests2yaml.py $(DESTDIR)$(PREFIX)/bin/morphTests2yaml
```

**Comment by kmurphy4** [comment]
I'm only vaguely familiar with `make`.  Is that invoking the `install(1)` command?

**Comment by keggsmurph21** [comment]
Also, if we're going down this rabbit hole, we could set up a [travis-ci](https://travis-ci.com/plans) pipeline for free since we're an open source project.

**Comment by jonorthwash** [comment]
> I'm only vaguely familiar with `make`. Is that invoking the `install(1)` command?

With that Makefile, you would just run `make install`, potentially with `sudo`, and it would execute the commands in the `install` block.

**Comment by jonorthwash** [comment]
> Also, if we're going down this rabbit hole, we could set up a [travis-ci](https://travis-ci.com/plans) pipeline for free since we're an open source project.

Yeah, that's the sort of thing I had in mind when I brought up virtualisation.  But that's a down-the-road sort of thing.  Maybe we could open an issue for it so we don't forget about it, and worry about it later.

**Comment by keggsmurph21** [comment]
> > I'm only vaguely familiar with `make`. Is that invoking the `install(1)` command?
> 
> With that Makefile, you would just run `make install`, potentially with `sudo`, and it would execute the commands in the `install` block.

Right, I understand that part of it.  I was curious about the actual contents of the `install` block (is "target" the right lingo?) though :)

**Comment by jonorthwash** [comment]
I'm actually not all that familiar with how `install` works, but `man install` gives some info.
